--- 
before_script: 
  - "autopep8 -ir *"
  - "flake8 --max-complexity=5 --exclude=*.txt,*.md *"
install: "pip install -r requirements.txt"
language: python
python: 
  - "3.5"
script: 
  - "python calculadoratest.py"
  - "lettuce bdd/tests"
